import type { InvestigationContext, NormalizedEvidence } from "./contracts.js";

const evidenceCitation = (ids: string[]): string => `[evidence: ${ids.join(", ")}]`;

export const renderContextMarkdown = (context: InvestigationContext): string => {
  const lines = [
    "# Production Bug Investigation",
    "",
    "> Use direct evidence and deterministic facts as authoritative.",
    "> Treat hypotheses as unproven and cite evidence IDs.",
    "",
    "## Problem",
    "",
    context.issue.title,
    "",
    `Occurred: ${context.issue.occurredAt}`,
    "",
    "## What is known",
    "",
    ...context.facts.flatMap((fact) => [
      `- ${fact.statement} ${evidenceCitation(fact.evidenceIds)}`,
    ]),
    "",
    "## Timeline",
    "",
    ...context.timeline.map(
      (event) =>
        `- ${event.timestamp} — ${event.summary} ${evidenceCitation(event.evidenceIds)}`,
    ),
    "",
    "## Evidence trail",
    "",
    ...context.searches.map(
      (search) =>
        `- ${search.intent.reason} Returned ${search.recordsAccepted} new records.`,
    ),
    "",
    "## Relevant entities",
    "",
    ...context.entities.map(
      (entity) =>
        `- \`${entity.kind}\`: ${entity.sensitivity === "personal" ? "[masked]" : `\`${entity.value}\``}`,
    ),
    "",
    "## Relevant code",
    "",
    ...context.issue.stackFrames.map(
      (frame) =>
        `- \`${frame.filename}${frame.lineNumber === undefined ? "" : `:${frame.lineNumber}`}\``,
    ),
    "",
    "## Hypotheses",
    "",
    ...(context.hypotheses.length === 0
      ? ["- No hypotheses were generated by the deterministic fixture investigation."]
      : context.hypotheses.map(
          (hypothesis) =>
            `- ${hypothesis.statement} ${evidenceCitation(hypothesis.evidenceIds)}`,
        )),
    "",
    "## Missing context",
    "",
    ...context.gaps.map((gap) => `- ${gap.description}`),
    "",
    "## Recommended next actions",
    "",
    "- Inspect the referenced stack frame using the evidence above.",
    "",
    "## Investigation limits",
    "",
    `- Stop reason: \`${context.completion.reason}\``,
    `- Queries executed: ${context.summary.searchCount}`,
    `- Evidence records accepted: ${context.summary.evidenceCount}`,
    "",
  ];
  return lines.join("\n");
};

export const renderTerminalSummary = (
  context: InvestigationContext,
  outputDirectory: string,
): string =>
  [
    `Tracecause investigation ${context.caseId}`,
    "",
    "Seed issue",
    `  ${context.issue.title}`,
    `  Occurred: ${context.issue.occurredAt}`,
    "",
    "Investigation complete",
    `  ${context.summary.evidenceCount} evidence records`,
    `  ${context.entities.length} related entities`,
    `  ${context.timeline.length} timeline events`,
    `  ${context.gaps.length} context gaps`,
    "",
    `Context: ${outputDirectory}/context.md`,
    `JSON:    ${outputDirectory}/context.json`,
  ].join("\n");

export const serializeEvidence = (evidence: NormalizedEvidence[]): string =>
  evidence.map((record) => JSON.stringify(record)).join("\n") + "\n";
